### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jennybc** [Reproducible-Science-Curriculum/rr-organization1#15]
@hlapp 

Sorry to ask this question at such a late moment.

I'm working on two sets of slides and want to know which license I should put on them. 

My standard template include CC-BY-NC and am wondering if I should edit that.

**Comment by hlapp** [comment]
Yes, could you edit that? We agreed at the workshop that the material would all be CC0. Is that possible? If not, can we agree on CC-BY? CC-BY-NC is not an open access license.

**Comment by jennybc** [comment]
I'm happy to change it. But not tonight! About to extract some literate programming / knitr / R markdown slides as well (will get the right the license on them to begin with).

**Comment by hlapp** [comment]
This was fixed in 56ea50eff7c30612b824caf49d40916626a6541c.
