### ISSUE TITLE
split into two lessons: Organization and Literate Programming

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-organization1#24]
At the [September 2015 sprint](https://github.com/Reproducible-Science-Curriculum/planning/wiki/Curriculum-development-sprint-Sep-2015) we discussed splitting this lesson into two separate lessons: 1. language-agnostic Organization; and 2. Literate Programming (in R now, but could add python lesson later).

**Comment by naupaka** [comment]
Starting work on this now.

**Comment by naupaka** [comment]
This lesson is now split into two: [rr-organization1](https://github.com/Reproducible-Science-Curriculum/rr-organization1) and [rr-literate-programming](https://github.com/Reproducible-Science-Curriculum/rr-literate-programming). @tracykteal will remove unnecessary/redundant content from rr-organization1 and I will remove the content/restructure rr-literature-programming.

**Comment by naupaka** [comment]
Done, closing.
