### ISSUE TITLE
standardize plotting commands in R

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-organization1#25]
At the first workshop, having some lessons use plot and some use ggplot was confusing. Maintainers of this repo and others that use R ([automation](https://github.com/Reproducible-Science-Curriculum/rr-automation)) should standardize to one plot method.

**Comment by mine-cetinkaya-rundel** [comment]
Very much agreed, I suggest `ggplot2`, that's what's used in the intro and organization lessons. Reasons for using ggplot2: easier to read with layers, more visually appealing by default (without too many lines of code for customization).

**Comment by naupaka** [comment]
I just checked, and all of the R code in both this repo (rr-organization1) and the sister repo (rr-literate-programming) use `ggplot` exclusively for plotting. So perhaps this issue on this repo can be closed @mine-cetinkaya-rundel @kcranston ?

**Comment by fmichonneau** [comment]
I'll open an issue in the rr-automation repo as it's there it needs to be fixed.
