### ISSUE TITLE
Eliminate redundancy of literate programming material here and into Intro lesson

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-organization1#27]
From first Duke workshop: In the literate programming section, much of the content in the slides feels redundant after the morning, or perhaps just needs trimming / reorganization (remember the things - Rmd, knitr, HTML generation - we saw this morning? here is some more detail…). 

Likely that this issue will get solved when we split this repo into two (issue #24) and remove the literate programming from the Intro lesson (https://github.com/Reproducible-Science-Curriculum/rr-intro/issues/10 ).

**Comment by naupaka** [comment]
Moved this issue to literate-programming repo https://github.com/Reproducible-Science-Curriculum/rr-literate-programming/issues/2
