### ISSUE TITLE
Need specific goals for literate programming exercise

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-organization1#28]
Feedback from Duke workshop: in the [literate programming section](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/03-literate-programming.md) make sure there are specific goals (Step 3?) rather than a general "now, go do some stuff" instruction.

**Comment by naupaka** [comment]
Moved this issue to the rr-literate-programming repo https://github.com/Reproducible-Science-Curriculum/rr-literate-programming/issues/3
