### ISSUE TITLE
03-literate-programming - R via RStudio

### ISSUE THREAD

**Issue by iamciera** [Reproducible-Science-Curriculum/rr-organization1#3]
Hi team @csoderberg, @jennybc, @naupaka, & kristina,

I was looking at the 03-literate-programming - R via RStudio section.  Correct me if I am wrong,  this whole section will consist of a guided tutorial.  I learned most of this from [lecture02_literate-programming-via-rmarkdown.md](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/lecture02_literate-programming-via-rmarkdown.md).  

From what I can tell, at the end of this session, the students should be able to:

1. Explain the advantages of literate programming.
2. Convey how "knitting works", file conversion ect.
3. Utilize markdown syntax.
3.  Differentiate between Input and output files.
4. Construct basic workflow for writing reproducible reports for their own work.

This all seems to be done with a guided tutorial taught by the instructor.  Were you guys envisioning a time that the students can explore the data on their own?  In the notes, it appears that @jennybc is putting together this lecture also. Is this still okay with you @jennybc?  Is there anyway I can help with this?  Any thoughts? 

I was thinking I could start by putting together a report on a specific country in both Word and RMarkdown...

**Comment by jennybc** [comment]
Hi @iamciera,

Your proposal to put together a country-specific report in Word and Rmd is great!

As for student exercise, you could imagine asking them to update the report for a different country or to change what computation or figure the report is making. If someone tried to do this for the Word and the Rmd, that really brings home the beauty of literate programming.

**Comment by iamciera** [comment]
@csoderberg, @jennybc, @naupaka,

You guys can have a look at the [report I made](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/files/03-literate-programming-activity/countryPick4.rmd).  Basically I didn't do just one country, because the visualizations are really boring. 

I have it so they pick four countries in the beginning, then all the code will form around the countries they pick.  I tried to make the plots and code as easy as possible in the beginning.  But with the all four country visualizations I stole @jennybc's great code a bit.

There is only one problem and that is that I copied the datafile into the directory so we don't have to worry about working directories.  **But now there are two copies of the data!!**

**Comment by naupaka** [comment]
Look good! Yeah the path issues with knitr-ing are frustrating. Not sure the best way to handle that... Maybe a relative path into the data directory? Which will make it work when knitted but not when run interactively in RStudio if the working directory is the root.
