### ISSUE TITLE
changing keynote slides to Rmd and using ioslides

### ISSUE THREAD

**Issue by tracykteal** [Reproducible-Science-Curriculum/rr-organization1#32]
In https://github.com/Reproducible-Science-Curriculum/rr-intro @mine-cetinkaya-rundel is using Rmd and ioslides to create the slides for the lesson. e.g. https://github.com/Reproducible-Science-Curriculum/rr-intro/blob/master/intro-01-slides.Rmd

It might be good to do that with these lessons as well. This has the advantage of being able to track changes in the slide files and can provide uniformity across the lessons.

**Comment by jennybc** [comment]
Sure I'll take help. I am more interesting in tackling the file naming piece than the project organization. I am currently sidetracked by my course that meet 9:30am :(

**Comment by mine-cetinkaya-rundel** [comment]
Completed.
