### ISSUE TITLE
Write lesson synopsis

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/rr-organization1#4]
As per Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014#26, a short synopsis (1-3 sentences) of this lesson's learning objectives is needed for the teaching workshop website: https://github.com/Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke/wiki/Lesson-synopses

Could this happen by the end of today (April 22)?

**Comment by naupaka** [comment]
I've just added a draft set for this session both to the README and to the wiki page you linked. Others should feel free to modify.
