### ISSUE TITLE
Seeking comments on draft mini lecture re: organization

### ISSUE THREAD

**Issue by jennybc** [Reproducible-Science-Curriculum/rr-organization1#5]
@iamciera @KristinaRiemer @csoderberg @naupaka @hlapp 

I drafted a mini lecture on organization. It really just narrates an example on my computer. Examples are so useful! But it's in Keynote at this point.

Would appreciate feedback re: content and what to do about the hurdle of format. For these kinds of slides, I shudder at the thought of attempting in R markdown or what have you. I should note I can't give this tons of time, so please keep the suggestions in line w/ time constraints.

For the moment, I'm developing here:

https://github.com/jennybc/organization-and-naming

And the first mini-lecture on organization is here:

https://github.com/jennybc/organization-and-naming/tree/master/organization

*scroll down and you can see each slide as a PNG*

I'll move on to naming files (and other things) and choosing the openest format possible.

**Comment by naupaka** [comment]
I like it! Only thing that gave me pause was the mention of makefiles - perhaps too soon?I love the ideas of the from_joe folder and taking away your own permissions on the raw data, and the first two slides do a great job of motivating the problem. As for format, I don't have any good answers, I'm afraid. Some of the slides would be very easy to port to (eg) slidify but others would be pretty tricky and would likely just be embedded images anyway. So, not sure how to best work that...

**Comment by pschloss** [comment]
I love the "...quarantine all the crazy here" idea and that you used a real world example

**Comment by iamciera** [comment]
Hi @jennybc,

I really like your slides for file organization.  I especially like the underlying message that projects evolve through time.  I also love how right right in the beginning - "Pick a strategy, any strategy, just pick one!".  Your real world "imperfect example" is great, but I agree with @naupaka, maybe hard to understand if they are not familiar with command line and make.  Maybe just start with a SUPER simple example, like the [noble diagram](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424)(?).   I think it is in basically completed shape and once you feel it is complete, you can put the keynote presentation file in the [files/03-literate-programming](https://github.com/Reproducible-Science-Curriculum/rr-organization1/tree/master/files/03-literate-programming) directory. 

I have been a little up-happy with the learning curve for layout control in html based slide programs, but I think I have a good handle on slidify at the moment and can convert your presentation later this month (after the first bootcamp).  Let's not worry too much about format of slides at this point.

**Comment by jennybc** [comment]
I can't tell if you're asking for a different example or just to write different things about the existing example. For example to not explain why the Makefile is there?

I briefly considered cooking up a fake real example based on the Gapminder data and stuff we're doing elsewhere in the workshop. But did not because [1] that would have taken more time and, more importantly [2] would have unnaturally tidy. It would not have included loose ends and, yes, the Makefile. I think the realism is good. But we can certainly just not address the presence of the Makefile.
