### ISSUE TITLE
Additions to Programmatic Modification

### ISSUE THREAD

**Issue by iamciera** [Reproducible-Science-Curriculum/rr-organization1#6]
Just wanted to get some thoughts put somewhere so I don't forget.  I have been going through everything trying to see the flow and I have two thoughts on the Programmatic Modification:

1. Maybe someone can make a script that does all the excel cleaning through programmatic modification using R? To show the power of a script running it?  Like a ta da moment.  Maybe for next bootcamp?  

2. Programmatic modification is something that takes a lot of time to learn. Maybe incorporate strategies of how to achieve this over time. Like when you have a problem, approach it as chance to learn R with YOUR material instead of a tutorial. It may take more time, but you are getting two things done at once; learning to code AND cleaning your data. Or if you never solve the problem, start a list of what you couldn’t do. Learn when you have more time.  

Thanks again @naupaka for the base! Looks great.

**Comment by iamciera** [comment]
Also, version control is left out completely in this course, since Organization 2 disbanded.  Could we fit a small introduction in here?  Just a thought.

**Comment by naupaka** [comment]
Hi @iamciera - just added a first pass effort on the script to do the cleaning as described in the instructors file. Take a look - not sure the best way to pull off the header/footer business in a clean way.

**Comment by naupaka** [comment]
Also just added a paragraph regarding your second point to the end of the lesson file.
