### ISSUE TITLE
Literate Programming Finishing 

### ISSUE THREAD

**Issue by iamciera** [Reproducible-Science-Curriculum/rr-organization1#7]
We were waiting for the introduction [activity 2 section](https://github.com/Reproducible-Science-Curriculum/rr-intro/blob/master/intro-02-template.Rmd) and now that I have seen both, it seems like [our section](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/files/03-literate-programming-activity/countryPick4.rmd) should focus on file input and output exclusively, but it may be nice for the students to reiterate some of the code they learned from the Introduction lesson (I wasn't expecting them to learn so much code!).  

We were not expecting to go into directory organization, but I think @jennybc's [lecture](https://github.com/jennybc/organization-and-naming/tree/master/organization) on directory structure is a perfect wrap-up.  **We still need to write an activity on file input and output to tie it all together**.  I can try to put something together in my down time, but my time is crazy limited this week (moving back to US, traveling, and giving talks).  If anyone feels they have a good plan...

Between both Intro and organization1 sections, we should try to make the R syntax as similar as possible.

**Comment by jennybc** [comment]
I still plan to write another little lecture on naming files. I WILL do that. Can you give a few more details on the needed exercise? I may very well have something can adapt easily….

**Comment by iamciera** [comment]
I am thinking of just guiding them through the files associated when knitting, but if they just use the Rstudio knit button, there is really only one file. An activity on file input and output is going to be hard to write and disseminate (files ect.). Maybe it will just have to be a discussion.  It goes back to why Organization 2 had so much disagreement - tackling paths and file input and output is hard to convey because each project is a unique snowflake.  Can you let me see the "something" so I can at least have more ideas and maybe you have good points I can include.

**Comment by jennybc** [comment]
OK check out these slides, which have some bits that explain the file flow when knitting.

https://github.com/jennybc/2015-02-23_bryan-fields-talk
https://speakerdeck.com/jennybc/new-tools-and-workflows-for-data-analysis

I can provide underlying Keynote for any of that. You might want to add something about what happens to PNGs that get created if you make a figure. My earlier project example will have great examples of that.

This stuff from my course also gives some much needed basic info on using the YAML to exert some control over which files get created and where they will be left.

http://stat545-ubc.github.io/block007_first-use-rmarkdown.html
https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/block007_first-use-rmarkdown.md

**Comment by iamciera** [comment]
Thank you @jennybc.  I spent some time today looking over the presentations and they are very useful.  The activity is great too!  Thanks.  I have some free time tomorrow and a 17 hour flight the next day, so hopefully I can finish everything up. 

**Version Control?**
@hlapp, @mine-cetinkaya-rundel, @fmichonneau, @kcranston  (+ others), one thought I had while looking at @jennybc's lecture material [https://speakerdeck.com/jennybc/new-tools-and-workflows-for-data-analysis](https://speakerdeck.com/jennybc/new-tools-and-workflows-for-data-analysis) is to briefly introduce version control in this section as a tie in to where to publish your R markdown reports.  Like super briefly, specifically slide 45 - 50 in the presentation above.  Is it ever covered anywhere else?  I think it is incredibly important to at least introduce it somewhere in the workshop.
